export type Locale = 'zh' | 'en';

export const copy = {
  zh: {
    languageName: 'EN',
    navStory: '理念',
    navProduct: 'PromptDock',
    navApply: '申请内测',
    eyebrow: 'CueGrove · 为专注而生',
    headline: '让灵感扎根，\n让工具生长。',
    heroBody: '我们创造安静、可靠、以隐私为先的个人工具，让每一个值得保留的想法都有生长的空间。',
    heroPrimary: '申请 PromptDock 内测',
    heroSecondary: '认识 CueGrove',
    signalPrivate: '本地优先',
    signalNative: '原生体验',
    signalCalm: '安静设计',
    storyKicker: '我们的理念',
    storyTitle: '工具不该争夺注意力，\n而该替你守住它。',
    storyBody: 'CueGrove 相信好的软件像一片林地：结构清晰、节奏自然，在你需要时可靠出现。我们从真实的个人工作流出发，把复杂能力收进简单、耐用的体验里。',
    valueOneTitle: '扎根本地',
    valueOneBody: '重要内容优先留在你的设备上。离线仍可工作，隐私不是附加选项。',
    valueTwoTitle: '顺着直觉',
    valueTwoBody: '每一个交互都服务于手头的任务，没有多余仪表盘，也不制造焦虑。',
    valueThreeTitle: '慢慢长好',
    valueThreeBody: '从可靠的核心开始，听取真实反馈，再让产品自然生长。',
    productKicker: '第一个产品',
    productTitle: 'PromptDock',
    productLead: '你的本地提示词资料库。',
    productBody: '为 macOS 打造的原生提示词工作台。快速整理、搜索、调用和备份，让高质量提示词随时就位。',
    featureSearch: '全局快搜',
    featureSearchBody: '用快捷键从任何地方唤起，找到并复制需要的提示词。',
    featureOrganize: '自然整理',
    featureOrganizeBody: '分类、收藏与自定义图标，让资料库保持清晰。',
    featurePrivacy: '隐私优先',
    featurePrivacyBody: '无需账号，内容保存在本机，也能完整导入与备份。',
    macRequirement: '专为 macOS 14+ 设计',
    applyKicker: 'PromptDock Early Access',
    applyTitle: '一起把它打磨得更好。',
    applyBody: '我们正在邀请一小群重视效率、隐私与细节的用户参与早期体验。告诉我们你的工作方式，我们会认真阅读每一份申请。',
    formName: '你的名字',
    formEmail: '邮箱',
    formRole: '你目前的角色',
    formRolePlaceholder: '请选择',
    roles: {
      student: '学生',
      creator: '创作者',
      developer: '开发者',
      researcher: '研究者',
      product: '产品 / 设计',
      other: '其他',
    },
    formUseCase: '你会怎样使用 PromptDock？',
    formUseCasePlaceholder: '例如：整理写作提示词、开发模板或研究工作流……',
    formReason: '为什么想参加 Early Access？',
    formReasonPlaceholder: '简单告诉我们你的期待，以及你愿意提供怎样的反馈。',
    consent: '我同意 CueGrove 使用以上信息审核本次申请并通过邮件联系我。',
    privacy: '我们只将申请信息用于 PromptDock Early Access 审核和联系，不出售信息，也不用于广告画像。',
    submit: '提交申请',
    submitting: '正在提交…',
    successTitle: '申请已经种下。',
    successBody: '谢谢你愿意参与。我们会认真阅读，并将审核结果发送到你的邮箱。',
    formError: '暂时无法提交，请稍后再试。',
    requiredError: '请完整填写所有字段并同意隐私说明。',
    turnstileRequired: '请先完成人机验证。',
    footerLine: '安静、可靠、尊重隐私的个人工具',
    footerPrivacy: '隐私说明',
    footerAdmin: '管理入口',
  },
  en: {
    languageName: '中文',
    navStory: 'Philosophy',
    navProduct: 'PromptDock',
    navApply: 'Apply',
    eyebrow: 'CueGrove · Built for focus',
    headline: 'Where ideas\ntake root.',
    heroBody: 'We build calm, dependable, privacy-first tools that give meaningful ideas room to grow.',
    heroPrimary: 'Apply for PromptDock',
    heroSecondary: 'Meet CueGrove',
    signalPrivate: 'Local first',
    signalNative: 'Native by design',
    signalCalm: 'Calm software',
    storyKicker: 'Our philosophy',
    storyTitle: 'Tools should protect\nyour attention.',
    storyBody: 'We believe good software feels like a grove: thoughtfully structured, naturally paced, and reliably there when needed. CueGrove turns complex capability into simple, durable tools built around real personal workflows.',
    valueOneTitle: 'Rooted locally',
    valueOneBody: 'Important work stays on your device first. Offline is normal, and privacy is never an add-on.',
    valueTwoTitle: 'Guided by instinct',
    valueTwoBody: 'Every interaction serves the work in front of you—without dashboards that demand attention.',
    valueThreeTitle: 'Grown with care',
    valueThreeBody: 'We begin with a dependable core, listen to real feedback, and let each product grow naturally.',
    productKicker: 'Our first product',
    productTitle: 'PromptDock',
    productLead: 'Your local prompt library.',
    productBody: 'A native macOS workspace for organizing, finding, using, and backing up your best prompts—right when you need them.',
    featureSearch: 'Search anywhere',
    featureSearchBody: 'Open Quick Search from anywhere, find the right prompt, and copy it in seconds.',
    featureOrganize: 'Stay organized',
    featureOrganizeBody: 'Categories, favorites, and custom icons keep a growing library easy to navigate.',
    featurePrivacy: 'Private by default',
    featurePrivacyBody: 'No account required. Your content stays on your Mac with complete backup and restore.',
    macRequirement: 'Designed for macOS 14+',
    applyKicker: 'PromptDock Early Access',
    applyTitle: 'Help us shape what grows next.',
    applyBody: 'We are inviting a small group of people who care about focus, privacy, and thoughtful details. Tell us how you work—we read every application.',
    formName: 'Your name',
    formEmail: 'Email address',
    formRole: 'What best describes you?',
    formRolePlaceholder: 'Select a role',
    roles: {
      student: 'Student',
      creator: 'Creator',
      developer: 'Developer',
      researcher: 'Researcher',
      product: 'Product / Design',
      other: 'Other',
    },
    formUseCase: 'How would you use PromptDock?',
    formUseCasePlaceholder: 'For example: writing prompts, development templates, or research workflows…',
    formReason: 'Why do you want Early Access?',
    formReasonPlaceholder: 'Tell us what you hope for and the kind of feedback you would share.',
    consent: 'I agree that CueGrove may use this information to review my application and contact me by email.',
    privacy: 'We only use application data to review and contact PromptDock Early Access applicants. We never sell it or use it for ad profiling.',
    submit: 'Submit application',
    submitting: 'Submitting…',
    successTitle: 'Your application is planted.',
    successBody: 'Thank you for taking part. We will read it carefully and send the decision to your email.',
    formError: 'We could not submit your application. Please try again later.',
    requiredError: 'Please complete every field and accept the privacy notice.',
    turnstileRequired: 'Please complete the human verification.',
    footerLine: 'Calm, dependable tools that respect your privacy',
    footerPrivacy: 'Privacy note',
    footerAdmin: 'Admin',
  },
} as const;
